$primary = rgb(2c6c13)
$surface = rgb(e3ebe0)
$secondary = rgb(165a25)
$error = rgb(fd4663)
$tertiary = rgb(194d3e)
$surface_lowest = rgb(f4f7f3)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
