// Copyright (c) 2026 Edward Luo. All rights reserved.
// This file is part of Vibe Island, a proprietary product.
// Unauthorized reproduction or distribution is prohibited.
// vibe-island-plugin-marker — auto-generated by Vibe Island
// version: v21
// OpenCode-compatible plugin: events + SyncEvent bridge + terminal env + permission/question reply
import { Socket } from "net";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const SOCKET = require("os").homedir() + "/.vibe-island/run/vibe-island.sock";

const _VI_SOURCE = "opencode";
const _VI_DISPLAY_NAME = "OpenCode";
const _VI_SESSION_PREFIX = "opencode";
const _VI_ENV_PREFIX = "OPENCODE";
    const _VI_DIRECTORY_HEADER = "x-opencode-directory";
    const _VI_AUTH_USERNAME = "opencode";
    const _VI_DESKTOP_BUNDLE_ID = "ai.opencode.desktop";
    const _VI_GLOBAL_EVENT_BRIDGE = "auto";

const _SIDECAR_USER = process.env[`${_VI_ENV_PREFIX}_SERVER_USERNAME`] || _VI_AUTH_USERNAME;
const _SIDECAR_PASSWORD = process.env[`${_VI_ENV_PREFIX}_SERVER_PASSWORD`];
const _AUTH_HEADER = _SIDECAR_PASSWORD
  ? "Basic " + Buffer.from(`${_SIDECAR_USER}:${_SIDECAR_PASSWORD}`).toString("base64")
  : null;

function prefixedSessionId(raw) {
  if (!raw || typeof raw !== "string") return raw;
  return raw.startsWith(`${_VI_SESSION_PREFIX}-`) ? raw : `${_VI_SESSION_PREFIX}-${raw}`;
}

function rawSessionId(sessionId) {
  const prefix = `${_VI_SESSION_PREFIX}-`;
  return sessionId?.startsWith(prefix) ? sessionId.slice(prefix.length) : sessionId;
}

function sendToSocket(json) {
  return new Promise((resolve) => {
    let settled = false;
    let wrote = false;
    const settle = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    try {
      const sock = new Socket();
      sock.on("error", () => settle(false));
      sock.on("close", () => settle(wrote));
      sock.on("connect", () => {
        try {
          sock.write(JSON.stringify(json));
          wrote = true;
          sock.end();
        } catch {
          sock.destroy();
          settle(false);
        }
      });
      sock.setTimeout(3000, () => { sock.destroy(); settle(false); });
      sock.connect({ path: SOCKET });
    } catch { settle(false); }
  });
}

function sendToSocketSync(json) {
  try {
    const result = require("child_process").spawnSync("/usr/bin/nc", ["-U", SOCKET], {
      input: JSON.stringify(json),
      timeout: 3000,
      stdio: ["pipe", "ignore", "ignore"],
    });
    return result.status === 0;
  } catch {
    return false;
  }
}

// Legacy socket negotiation (retained for protocol backward compat)
function _negotiateFallback(path) {
  const h = path.split("").reduce((a, c) => ((a << 5) - a + c.charCodeAt(0)) | 0, 5381);
  return `/tmp/.vi-${(h >>> 0).toString(36)}.sock`;
}

function sendAndWaitResponse(json, timeoutMs = 300000) {
  return new Promise((resolve) => {
    let settled = false;
    const settle = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    try {
      const sock = new Socket();
      let buf = "";
      sock.on("error", () => settle(null));
      sock.on("data", (data) => { buf += data.toString(); });
      sock.on("end", () => {
        try { settle(JSON.parse(buf)); } catch { settle(null); }
      });
      sock.on("connect", () => {
        try {
          sock.write(JSON.stringify(json));
        } catch {
          sock.destroy();
          settle(null);
        }
      });
      sock.setTimeout(timeoutMs, () => { sock.destroy(); settle(null); });
      sock.connect({ path: SOCKET });
    } catch { settle(null); }
  });
}

export default async ({ client, serverUrl, directory }) => {
  const pid = process.pid;
  const serverOrigin = serverUrl?.origin || "http://127.0.0.1:4096";

  function buildHeaders(cwd) {
    const headers = { "Content-Type": "application/json" };
    if (_AUTH_HEADER) headers.Authorization = _AUTH_HEADER;
    const dir = cwd || directory;
    if (dir) headers[_VI_DIRECTORY_HEADER] = encodeURIComponent(dir);
    return headers;
  }

  async function postReply(path, body, cwd) {
    try {
      const response = await fetch(`${serverOrigin}${path}`, {
        method: "POST", headers: buildHeaders(cwd), body: JSON.stringify(body),
      });
      if (response?.ok) return response;
    } catch {}
    const port = parseInt(serverUrl?.port) || 4096;
    const shouldUseClientFallback = !_AUTH_HEADER && port === 4096;
    if (!shouldUseClientFallback) return null;
    try {
      const rawClient = client?._client;
      if (!rawClient?.post) return null;
      return await rawClient.post({ url: path, headers: buildHeaders(cwd), body });
    } catch { return null; }
  }

  const msgRoles = new Map();
  const sessions = new Map();
  const knownSessions = new Set();
  const partBuffers = new Map();
  const pendingPartsByMessage = new Map();
  const recentStops = new Map();
  const seenEvents = new Map();
  const sessionCwd = new Map();

  function isInformativeTitle(title) {
    return title && !title.startsWith("New session");
  }

  function getSession(sid) {
    if (!sessions.has(sid)) sessions.set(sid, { lastUserText: "", lastAssistantText: "" });
    return sessions.get(sid);
  }

  function normalizeParentSessionId(raw) {
    if (!raw || typeof raw !== "string") return undefined;
    return prefixedSessionId(raw);
  }

  function sessionParentId(info) {
    return normalizeParentSessionId(info?.parentID || info?.parentId || info?.parent_id);
  }

  async function fetchSessionInfo(sessionId, cwd) {
    const path = `/session/${encodeURIComponent(sessionId)}`;
    try {
      const response = await fetch(`${serverOrigin}${path}`, {
        method: "GET", headers: buildHeaders(cwd),
      });
      if (response?.ok) return await response.json();
    } catch {}
    try {
      const response = await fetch(`${serverOrigin}/session`, {
        method: "GET", headers: buildHeaders(cwd),
      });
      if (response?.ok) {
        const sessions = await response.json();
        if (Array.isArray(sessions)) return sessions.find((s) => s?.id === sessionId) || null;
      }
    } catch {}
    const port = parseInt(serverUrl?.port) || 4096;
    const shouldUseClientFallback = !_AUTH_HEADER && port === 4096;
    if (!shouldUseClientFallback) return null;
    try {
      const rawClient = client?._client;
      if (!rawClient?.get) return null;
      const result = await rawClient.get({ url: path, headers: buildHeaders(cwd) });
      return result?.data || result || null;
    } catch { return null; }
  }

  function rememberSessionInfo(info) {
    if (!info?.id) return;
    if (info.directory) sessionCwd.set(info.id, info.directory);
    const s = getSession(info.id);
    const parentID = sessionParentId(info);
    if (parentID) s.parentID = parentID;
    if (isInformativeTitle(info.title)) s.pendingTitle = info.title;
  }

  async function hydrateMapped(mapped) {
    if (!mapped?.session_id?.startsWith(`${_VI_SESSION_PREFIX}-`)) return mapped;
    if (mapped.hook_event_name === "SessionEnd") return mapped;
    const rawId = rawSessionId(mapped.session_id);
    const s = getSession(rawId);
    if (!mapped.cwd) {
      mapped.cwd = sessionCwd.get(rawId) || directory || undefined;
    }
    if (!mapped._opencode_parent_id && s.parentID) {
      mapped._opencode_parent_id = s.parentID;
    }
    if (!mapped.codex_title && isInformativeTitle(s.pendingTitle)) {
      mapped.codex_title = s.pendingTitle;
    }
    if (mapped.hook_event_name === "Stop") return mapped;
    const needsParentHydration = mapped.hook_event_name === "SessionStart" && !mapped._opencode_parent_id;
    if (!mapped.cwd || !mapped.codex_title || needsParentHydration) {
      const info = await fetchSessionInfo(rawId, mapped.cwd);
      if (info) {
        rememberSessionInfo(info);
        if (!mapped.cwd && info.directory) mapped.cwd = info.directory;
        if (!mapped.codex_title && isInformativeTitle(info.title)) mapped.codex_title = info.title;
        if (!mapped._opencode_parent_id) mapped._opencode_parent_id = sessionParentId(info);
      }
    }
    return mapped;
  }

    const ENV_KEYS = [
    "TERM_PROGRAM", "ITERM_SESSION_ID", "TERM_SESSION_ID",
    "TMUX", "TMUX_PANE", "KITTY_WINDOW_ID", "__CFBundleIdentifier",
    "CONDUCTOR_WORKSPACE_NAME", "CONDUCTOR_PORT", "CURSOR_TRACE_ID",
    "CMUX_WORKSPACE_ID", "CMUX_SURFACE_ID", "CMUX_SOCKET_PATH",
    "OTTY_SOCKET", "OTTY_PANE_ID",
    "WINDOWSERVER_DISPLAY_UUID",
  ];

  let detectedTty = null;
  try {
    const { execSync } = require("child_process");
    let walkPid = process.pid;
    for (let i = 0; i < 8; i++) {
      const info = execSync(`ps -o tty=,ppid= -p ${walkPid}`, { timeout: 1000 }).toString().trim();
      const parts = info.split(/\s+/);
      const tty = parts[0], ppid = parseInt(parts[1]);
      if (tty && tty !== "??" && tty !== "?") { detectedTty = `/dev/${tty}`; break; }
      if (!ppid || ppid <= 1) break;
      walkPid = ppid;
    }
  } catch {}

  function collectEnv() {
    const env = {};
    for (const k of ENV_KEYS) { if (process.env[k]) env[k] = process.env[k]; }
    if (process.env[`${_VI_ENV_PREFIX}_CLIENT`] === "desktop" && _VI_DESKTOP_BUNDLE_ID && !env.__CFBundleIdentifier) {
      env.__CFBundleIdentifier = _VI_DESKTOP_BUNDLE_ID;
    }
    return env;
  }

  const termProg = process.env.TERM_PROGRAM || "";
  const isOsc2Terminal = ["ghostty", "xterm-ghostty"].includes(termProg) && !process.env.TMUX;
  let displayTitle = null;

  function setTabTitle(sessionId, cwd, userText, aiTitle) {
    if (!isOsc2Terminal) return;
    const project = (cwd || process.env.PWD || "session").split("/").pop() || "session";
    const prefix = rawSessionId(sessionId).slice(0, 16);
    if (aiTitle) {
      displayTitle = aiTitle.replace(/\n/g, " ").slice(0, 30);
    } else if (!displayTitle && userText) {
      displayTitle = userText.replace(/\n/g, " ").slice(0, 30);
    }
    const title = displayTitle
      ? `${project} · ${displayTitle} · ${prefix}`
      : `${project} · ${prefix}`;
    const osc = `\x1b]2;${title}\x07`;
    if (detectedTty) {
      try {
        const fs = require("fs");
        fs.writeFileSync(detectedTty, osc);
      } catch {}
    }
    try {
      const fs = require("fs");
      const os = require("os");
      const osc2Dir = `${os.homedir()}/.vibe-island/cache/osc2-titles`;
      try { fs.mkdirSync(osc2Dir, { recursive: true }); } catch {}
      fs.writeFileSync(`${osc2Dir}/${prefix}`, displayTitle || "");
    } catch {}
  }

  function base(sessionId, extra) {
    return {
      session_id: sessionId,
      _source: _VI_SOURCE,
      _ppid: pid,
      _env: collectEnv(),
      _tty: detectedTty,
      _server_port: parseInt(serverUrl?.port) || 4096,
      ...extra,
    };
  }

  function cleanupSeen(now) {
    if (seenEvents.size <= 500) return;
    const cutoff = now - 10 * 60 * 1000;
    for (const [key, ts] of seenEvents) {
      if (ts < cutoff || seenEvents.size > 800) seenEvents.delete(key);
      if (seenEvents.size <= 500) break;
    }
  }

  function eventKey(ev) {
    if (ev?.id) return `id:${ev.id}`;
    const p = ev?.properties || {};
    const part = p.part || {};
    const status = p.status?.type || part.state?.status || "";
    return [
      "fallback", ev?.type || "", p.sessionID || p.info?.sessionID || part.sessionID || p.info?.id || "",
      p.messageID || p.info?.id || part.messageID || "", p.partID || part.id || p.id || "", status,
    ].join(":");
  }

  function shouldProcessEvent(ev) {
    const key = eventKey(ev);
    if (!key) return true;
    if (seenEvents.has(key)) return false;
    const now = Date.now();
    seenEvents.set(key, now);
    cleanupSeen(now);
    return true;
  }

  function normalizeSyncEventType(type) {
    return (type || "").replace(/\.\d+$/, "");
  }

  function syncEventToBusEvent(syncEvent) {
    const type = normalizeSyncEventType(syncEvent?.type);
    if (!["session.created", "session.updated", "session.deleted",
      "session.status", "session.idle",
      "message.updated", "message.part.updated", "message.part.delta",
      "permission.asked", "permission.replied",
      "question.asked", "question.replied", "question.rejected"].includes(type)) return null;
    return { id: syncEvent.id, type, properties: syncEvent.data || {} };
  }

  function rememberPendingPart(part) {
    if (!part?.messageID) return;
    const list = pendingPartsByMessage.get(part.messageID) || [];
    list.push(part);
    pendingPartsByMessage.set(part.messageID, list.slice(-20));
    if (pendingPartsByMessage.size > 200) pendingPartsByMessage.delete(pendingPartsByMessage.keys().next().value);
  }

  function markSessionStarted(sessionId, cwd, parentID) {
    if (!sessionId) return null;
    const sessionState = getSession(sessionId);
    const effectiveCwd = cwd || directory || undefined;
    if (effectiveCwd) sessionCwd.set(sessionId, effectiveCwd);
    const extra = { hook_event_name: "SessionStart", cwd: effectiveCwd };
    if (parentID) extra._opencode_parent_id = parentID;
    if (knownSessions.has(sessionId)) {
      if (parentID && sessionState.parentEmitted !== parentID) {
        sessionState.parentEmitted = parentID;
        return base(prefixedSessionId(sessionId), extra);
      }
      return null;
    }
    knownSessions.add(sessionId);
    if (parentID) sessionState.parentEmitted = parentID;
    return base(prefixedSessionId(sessionId), extra);
  }

  function markSessionStopped(sessionId, stopSource = "native-idle") {
    if (!sessionId) return null;
    const now = Date.now();
    const last = recentStops.get(sessionId) || 0;
    if (now - last < 1500) return null;
    recentStops.set(sessionId, now);
    const sid = prefixedSessionId(sessionId);
    const s = getSession(sessionId);
    const cwd = sessionCwd.get(sessionId);
    const extra = { hook_event_name: "Stop", cwd,
      _opencode_stop_source: stopSource,
      last_assistant_message: s.lastAssistantText || undefined,
      model: s.lastModel || undefined };
    if (s.pendingTitle) { extra.codex_title = s.pendingTitle; s.pendingTitle = null; }
    return base(sid, extra);
  }

  function mapEvent(ev) {
    const t = ev.type;
    const p = ev.properties || {};

    if (t === "session.created" && p.info) {
      const cwd = p.info.directory || "";
      sessionCwd.set(p.info.id, cwd);
      const parentID = sessionParentId(p.info);
      if (parentID) getSession(p.info.id).parentID = parentID;
      return markSessionStarted(p.info.id, cwd, parentID);
    }
    if (t === "session.deleted" && p.info) {
      sessions.delete(p.info.id); sessionCwd.delete(p.info.id); knownSessions.delete(p.info.id);
      return base(prefixedSessionId(p.info.id), { hook_event_name: "SessionEnd" });
    }
    if (t === "session.updated" && p.info) {
      if (p.info.directory) sessionCwd.set(p.info.id, p.info.directory);
      if (p.info.time?.archived) {
        sessions.delete(p.info.id); sessionCwd.delete(p.info.id); knownSessions.delete(p.info.id);
        return base(prefixedSessionId(p.info.id), { hook_event_name: "SessionEnd" });
      }
      if (isInformativeTitle(p.info.title)) {
        const s = getSession(p.info.id);
        s.pendingTitle = p.info.title;
        setTabTitle(prefixedSessionId(p.info.id), sessionCwd.get(p.info.id), null, p.info.title);
      }
      const parentID = sessionParentId(p.info);
      if (parentID) getSession(p.info.id).parentID = parentID;
      return markSessionStarted(p.info.id, sessionCwd.get(p.info.id), parentID);
    }
    if ((t === "session.status" || t === "session.idle") && p.sessionID) {
      if (t === "session.idle" || p.status?.type === "idle") {
        return markSessionStopped(p.sessionID, t === "session.idle" ? "session.idle" : "session.status-idle");
      }
    }

    if (t === "message.updated" && p.info?.id && p.info?.sessionID) {
      msgRoles.set(p.info.id, { role: p.info.role, sessionID: p.info.sessionID });
      if (msgRoles.size > 200) { msgRoles.delete(msgRoles.keys().next().value); }
      // SUP-524: capture assistant model id, attached to the Stop payload below for the card tag
      if (p.info.role === "assistant" && p.info.modelID) { getSession(p.info.sessionID).lastModel = p.info.modelID; }
      const pending = pendingPartsByMessage.get(p.info.id) || [];
      pendingPartsByMessage.delete(p.info.id);
      const mapped = pending.map((part) => mapEvent({
        type: "message.part.updated",
        properties: { sessionID: p.info.sessionID, part },
      })).filter(Boolean).flat();
      return mapped;
    }
    if (t === "message.part.updated" && p.part?.type === "text" && p.part?.messageID) {
      const meta = msgRoles.get(p.part.messageID);
      if (!meta) { rememberPendingPart(p.part); return null; }
      const s = getSession(meta.sessionID);
      const cwd = sessionCwd.get(meta.sessionID);
      const text = p.part.text || "";
      if (meta.role === "user" && text) {
        s.lastUserText = text;
        return base(prefixedSessionId(meta.sessionID), {
          hook_event_name: "UserPromptSubmit", cwd, prompt: text });
      }
      if (meta.role === "assistant" && text) { s.lastAssistantText = text; }
      return null;
    }
    if (t === "message.part.updated" && p.part?.type === "tool" && p.part?.sessionID) {
      if (p.part.messageID && !msgRoles.has(p.part.messageID)) {
        rememberPendingPart(p.part);
        return null;
      }
      const sid = prefixedSessionId(p.part.sessionID);
      const st = p.part.state?.status;
      const cwd = sessionCwd.get(p.part.sessionID);
      const toolName = (p.part.tool || "").charAt(0).toUpperCase() + (p.part.tool || "").slice(1);
      if (st === "running" || st === "pending") {
        return base(sid, { hook_event_name: "PreToolUse", cwd, tool_name: toolName,
          tool_input: p.part.state?.input || {} });
      }
      if (st === "completed" || st === "error") {
        return base(sid, { hook_event_name: "PostToolUse", cwd, tool_name: toolName });
      }
    }
    if (t === "message.part.delta" && p.sessionID && p.partID && p.field === "text") {
      const key = `${p.sessionID}:${p.partID}`;
      const next = (partBuffers.get(key) || "") + (p.delta || "");
      partBuffers.set(key, next);
      if (partBuffers.size > 200) partBuffers.delete(partBuffers.keys().next().value);
      getSession(p.sessionID).lastAssistantText = next;
      return null;
    }
    if (t === "permission.asked" && p.id && p.sessionID) {
      const toolName = (p.permission || "").charAt(0).toUpperCase() + (p.permission || "").slice(1);
      const patterns = p.patterns || [];
      const toolInput = { patterns, metadata: p.metadata };
      if (p.permission === "bash" && patterns.length > 0) {
        toolInput.command = patterns.join(" && ");
      }
      if ((p.permission === "edit" || p.permission === "write") && patterns.length > 0) {
        toolInput.file_path = patterns[0];
      }
      return base(prefixedSessionId(p.sessionID), { hook_event_name: "PermissionRequest",
        cwd: sessionCwd.get(p.sessionID), tool_name: toolName,
        tool_input: toolInput,
        _opencode_request_id: p.id });
    }
    if (t === "permission.replied" && p.sessionID) {
      return base(prefixedSessionId(p.sessionID), { hook_event_name: "PostToolUse",
        cwd: sessionCwd.get(p.sessionID), _opencode_request_id: p.requestID });
    }
    if (t === "question.asked" && p.id && p.sessionID) {
      const questions = (p.questions || []).map(q => ({
        question: q.question || "",
        header: q.header || "",
        options: (q.options || []).map(o => ({ label: o.label, description: o.description })),
        multiSelect: q.multiple || false,
      }));
      return base(prefixedSessionId(p.sessionID), { hook_event_name: "PermissionRequest",
        cwd: sessionCwd.get(p.sessionID), tool_name: "AskUserQuestion",
        tool_input: { questions }, _opencode_request_id: p.id });
    }
    if ((t === "question.replied" || t === "question.rejected") && p.sessionID) {
      return base(prefixedSessionId(p.sessionID), { hook_event_name: "PostToolUse",
        cwd: sessionCwd.get(p.sessionID), _opencode_request_id: p.requestID });
    }
    return null;
  }

  async function dispatchMapped(mapped) {
    if (!mapped) return;
    if (Array.isArray(mapped)) {
      for (const item of mapped) await dispatchMapped(item);
      return;
    }
    mapped = await hydrateMapped(mapped);
    if (mapped.hook_event_name === "SessionStart") {
      setTabTitle(mapped.session_id, mapped.cwd, null);
    } else if (mapped.hook_event_name === "UserPromptSubmit" && mapped.prompt) {
      setTabTitle(mapped.session_id, null, mapped.prompt);
    }
    if (mapped.hook_event_name === "PermissionRequest" && mapped.tool_name === "AskUserQuestion") {
      const requestId = mapped._opencode_request_id;
      const cwd = mapped.cwd;
      sendAndWaitResponse(mapped).then(async (response) => {
        if (!response) return;
        const answers = response?.hookSpecificOutput?.decision?.updatedInput?.answers;
        if (!answers) return;
        const qs = mapped.tool_input?.questions || [];
        const answerArray = qs.length > 0
          ? qs.map(q => answers[q.header] ? [answers[q.header]] : []).filter(a => a.length > 0)
          : Object.values(answers).map(v => [v]);
        await postReply(`/question/${requestId}/reply`, { answers: answerArray }, cwd);
      });
      return;
    }
    if (mapped.hook_event_name === "PermissionRequest") {
      const requestId = mapped._opencode_request_id;
      const cwd = mapped.cwd;
      sendAndWaitResponse(mapped).then(async (response) => {
        if (!response) return;
        const behavior = response?.hookSpecificOutput?.decision?.behavior;
        const reason = response?.hookSpecificOutput?.decision?.reason;
        if (!behavior) return;
        const reply = behavior === "allow" ? "once"
          : behavior === "always" ? "always" : "reject";
        await postReply(`/permission/${requestId}/reply`, { reply, message: reason }, cwd);
      });
      return;
    }
    if (mapped.hook_event_name === "Stop" && sendToSocketSync(mapped)) return;
    await sendToSocket(mapped);
  }

  async function dispatchEvent(event) {
    if (!event || !shouldProcessEvent(event)) return;
    await dispatchMapped(mapEvent(event));
  }

  function shouldConsumeGlobalEvent(globalEvent) {
    if (!globalEvent?.payload) return false;
    if (globalEvent.directory && directory && globalEvent.directory !== directory) return false;
    return true;
  }

  function handleGlobalSseChunk(chunk) {
    const data = chunk.split(/\r?\n/)
      .filter((line) => line.startsWith("data:"))
      .map((line) => line.slice(5).trimStart())
      .join("\n");
    if (!data) return;
    try {
      const globalEvent = JSON.parse(data);
      if (!shouldConsumeGlobalEvent(globalEvent)) return;
      const payload = globalEvent.payload || {};
      if (payload.type !== "sync") return;
      const event = syncEventToBusEvent(payload.syncEvent);
      if (event) void dispatchEvent(event);
    } catch {}
  }

      async function startGlobalEventBridge() {
        const shouldStart = _VI_GLOBAL_EVENT_BRIDGE === "always"
          || process.env[`${_VI_ENV_PREFIX}_CLIENT`] === "desktop"
          || Boolean(_AUTH_HEADER)
          || (serverUrl?.port && parseInt(serverUrl.port) !== 4096);
        if (!shouldStart) return;

        const bridgeDelay = (ms) => new Promise((resolve) => {
          const timer = setTimeout(resolve, ms);
          if (timer?.unref) timer.unref();
        });

        let delay = 1000;
        while (true) {
      try {
        const response = await fetch(`${serverOrigin}/global/event`, {
          method: "GET",
          headers: buildHeaders(directory),
        });
        if (!response?.ok || !response.body) throw new Error("global event unavailable");
        delay = 1000;
        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";
        while (true) {
          const { value, done } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          buffer = buffer.replace(/\r\n/g, "\n");
          let idx;
          while ((idx = buffer.indexOf("\n\n")) !== -1) {
            const chunk = buffer.slice(0, idx);
            buffer = buffer.slice(idx + 2);
            handleGlobalSseChunk(chunk);
          }
        }
      } catch {}
          await bridgeDelay(delay);
          delay = Math.min(delay * 2, 30000);
        }
      }

  void startGlobalEventBridge();

  return {
    "event": async ({ event }) => {
      await dispatchEvent(event);
    },
    "shell.env": async (input, output) => {
      for (const v of ["TERM_PROGRAM","ITERM_SESSION_ID","TERM_SESSION_ID",
        "TMUX","TMUX_PANE","KITTY_WINDOW_ID","__CFBundleIdentifier",
        "CMUX_WORKSPACE_ID","CMUX_SURFACE_ID","CMUX_SOCKET_PATH"]) {
        if (process.env[v]) output.env["_VI_" + v] = process.env[v];
      }
    },
  };
};