ln -sf ~/dots/mac/borders ~/.config/borders
ln -sf ~/dots/mac/btop ~/.config/btop
ln -sf ~/dots/mac/fastfetch ~/.config/fastfetch
ln -sf ~/dots/mac/kitty ~/.config/kitty
ln -sf ~/dots/mac/nvim ~/.config/nvim
ln -sf ~/dots/mac/sketchybar ~/.config/sketchybar
ln -sf ~/dots/mac/skhd ~/.config/skhd
ln -sf ~/dots/mac/tmux ~/.config/tmux
ln -sf ~/dots/mac/yabai ~/.config/yabai
ln -sf ~/dots/mac/colorswap.sh ~/.config/colorswap.sh
ln -sf ~/dots/mac/ghostty ~/.config/ghostty
