require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.gpu")
require("items.widgets.cpu")
require("items.widgets.weather")
require("items.widgets.vpn")
require("items.widgets.wifi")
