ln -sf ~/dots/arch/anyrun ~/.config/anyrun
ln -sf ~/dots/arch/btop ~/.config/btop
ln -sf ~/dots/arch/Thunar ~/.config/Thunar
ln -sf ~/dots/arch/fastfetch ~/.config/fastfetch
ln -sf ~/dots/arch/gtk-3.0 ~/.config/gtk-3.0
ln -sf ~/dots/arch/gwe ~/.config/gwe
ln -sf ~/dots/arch/hypr ~/.config/hypr
ln -sf ~/dots/arch/kitty ~/.config/kitty
ln -sf ~/dots/arch/menus ~/.config/menus
ln -sf ~/dots/arch/nvim ~/.config/nvim
ln -sf ~/dots/arch/nwg-look ~/.config/nwg-look
ln -sf ~/dots/arch/tmux ~/.config/tmux
ln -sf ~/dots/arch/waybar ~/.config/waybar
ln -sf ~/dots/arch/xfce4 ~/.config/xfce4
ln -sf ~/dots/arch/xsettingsd ~/.config/xsettingsd
ln -sf ~/dots/arch/wallpapers ~/.config/wallpapers
ln -sf ~/dots/arch/kidex.ron ~/.config/kidex.ron
