color0 #1c2518
color1 #fd4663
color2 #8ae467
color3 #5cd677
color4 #66ccb0
color5 #acec93
color6 #96e9a8
color7 #f2f3f2
color8 #62705c
color9 #fd4663
color10 #8ae467
color11 #5cd677
color12 #66ccb0
color13 #acec93
color14 #96e9a8
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1c2518
background            #1c2518
foreground            #f2f3f2
selection_foreground  #b1b6af
selection_background  #253220
active_border_color   #8ae467
inactive_border_color #253220
url_color             #8ae467

active_tab_foreground   #1c2518
active_tab_background   #8ae467
inactive_tab_foreground #b1b6af
inactive_tab_background #253220
cursor_trail_color      #b1b6af
