color0 #e3ebe0
color1 #fd4663
color2 #2c6c13
color3 #165a25
color4 #194d3e
color5 #358217
color6 #1b7e31
color7 #191b18
color8 #679056
color9 #fd4663
color10 #2c6c13
color11 #165a25
color12 #194d3e
color13 #358217
color14 #1b7e31
color15 #191b18

cursor                #191b18
cursor_text_color     #e3ebe0
background            #e3ebe0
foreground            #191b18
selection_foreground  #535a52
selection_background  #c1d3bb
active_border_color   #2c6c13
inactive_border_color #c1d3bb
url_color             #2c6c13

active_tab_foreground   #fafaf9
active_tab_background   #2c6c13
inactive_tab_foreground #535a52
inactive_tab_background #c1d3bb
cursor_trail_color      #535a52
